# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

solve_least_sq_via_qr_cpp_eig <- function(X, y) {
    .Call(`_hiperglm_solve_least_sq_via_qr_cpp_eig`, X, y)
}

